appname = creator
httpport = 8080
runmode = dev
sessionon = true

creator_bot_token = 8802977388:AAFGp9EQkn5pJb8QeC_1Uo8DjF4GkDMcluU

[dev]
db_host = localhost
db_name = creator
db_port = 5432
db_user = admin
db_pass = admin

admin_panel_pass = F$P76QKnF$P76QKn

[prod]
db_host = localhost
db_name = shadowing
db_user = oke4tgd
db_pass = okefgrtgh